In [1]:
%display latex

In [7]:
import numpy as np

In [2]:
A = matrix([[2,0],[0,-.25]])
S = matrix([[1/sqrt(2),0],[0,2]])

S*A*S

[ 1.00000000000000                 0]
[                0 -1.00000000000000]

In [3]:
M = matrix([[0,-2,1],[-1,-1,1],[-1,-2,2]])

In [5]:
M^2

[1 0 0]
[0 1 0]
[0 0 1]

In [21]:
I = matrix.identity(3)

In [22]:
I

[1 0 0]
[0 1 0]
[0 0 1]

In [25]:
M_prime = I-M

M_prime

[ 1  2 -1]
[ 1  2 -1]
[ 1  2 -1]

In [26]:
var('x,y,z')
X = vector([x,y,z])

In [27]:
M_prime*X

(x + 2*y - z, x + 2*y - z, x + 2*y - z)